package io.github.jukomu.picacomic.core.net.interceptor;

import io.github.jukomu.picacomic.core.constant.PicaConstants;
import io.github.jukomu.picacomic.core.net.provider.PicaDomainManager;
import okhttp3.HttpUrl;
import okhttp3.Interceptor;
import okhttp3.Request;
import okhttp3.Response;
import org.jetbrains.annotations.NotNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.util.List;

/**
 * API 专用的有界直连重试拦截器。
 *
 * <p>它只在已经授权的 API host 之间轮换，只对幂等 GET/HEAD 以及 502/503/504
 * 或 I/O 错误重试。图片 client 不安装此拦截器。</p>
 */
public final class RetryAndDomainRedirectInterceptor implements Interceptor {

    private static final Logger LOGGER = LoggerFactory.getLogger(RetryAndDomainRedirectInterceptor.class);

    private final PicaDomainManager domainManager;
    private final int maxRetries;

    /**
     * @param maxRetries 首次尝试之后的额外尝试次数
     * @param domainManager 当前 client 的 API host 管理器
     */
    public RetryAndDomainRedirectInterceptor(int maxRetries, PicaDomainManager domainManager) {
        if (maxRetries < 0) {
            throw new IllegalArgumentException("Max retries must be non-negative");
        }
        this.maxRetries = maxRetries;
        this.domainManager = domainManager;
    }

    @NotNull
    @Override
    public Response intercept(@NotNull Chain chain) throws IOException {
        Request original = chain.request();
        boolean retryableMethod = "GET".equalsIgnoreCase(original.method())
                || "HEAD".equalsIgnoreCase(original.method());
        List<String> orderedDomains = domainManager.snapshotInPriorityOrder();
        if (orderedDomains.isEmpty()) {
            throw new IOException("No API domain is available");
        }

        IOException lastException = null;
        for (int attempt = 0; attempt <= maxRetries; attempt++) {
            if (attempt > 0 && chain.call().isCanceled()) {
                if (lastException != null) {
                    throw lastException;
                }
                throw new IOException("API request was cancelled");
            }
            if (attempt > 0 && deadlineReached(chain)) {
                if (lastException != null) {
                    throw lastException;
                }
                throw new IOException("API request deadline reached");
            }

            String host = orderedDomains.get(attempt % orderedDomains.size());
            Request request = buildAttemptRequest(original, host);
            try {
                Response response = chain.proceed(request);
                int status = response.code();
                if (status >= 200 && status <= 299) {
                    domainManager.reportSuccess(host);
                    return response;
                }

                if (retryableMethod && isRetryableStatus(status) && attempt < maxRetries) {
                    response.close();
                    domainManager.reportFailure(host);
                    LOGGER.debug("API request host={} attempt={} status={} retrying", host, attempt + 1, status);
                    continue;
                }

                return response;
            } catch (IOException exception) {
                lastException = exception;
                if (!retryableMethod || attempt >= maxRetries || chain.call().isCanceled()
                        || deadlineReached(chain)) {
                    throw exception;
                }
                domainManager.reportFailure(host);
                LOGGER.debug("API request host={} attempt={} io={} retrying", host, attempt + 1,
                        exception.getClass().getSimpleName());
            }
        }

        throw lastException == null ? new IOException("API request failed") : lastException;
    }

    private Request buildAttemptRequest(Request original, String host) throws IOException {
        HttpUrl originalUrl = original.url();
        if (!PicaConstants.PLACEHOLDER_HOST.equals(originalUrl.host())
                && !domainManager.contains(originalUrl.host())) {
            throw new IOException("API request target is not an authorized host");
        }
        HttpUrl attemptUrl = originalUrl.newBuilder().host(host).build();
        // Host is generated by OkHttp for the validated URL; an input Host header cannot override it.
        return original.newBuilder()
                .url(attemptUrl)
                .removeHeader("Host")
                .build();
    }

    private static boolean isRetryableStatus(int status) {
        return status == 502 || status == 503 || status == 504;
    }

    private static boolean deadlineReached(Chain chain) {
        return chain.call().timeout().hasDeadline()
                && chain.call().timeout().deadlineNanoTime() <= System.nanoTime();
    }
}
