[versions]
agp = "8.10.1"
compileSdk = "36"
minSdk = "24"
targetSdk = "36"
picacomic = "0.1.0-rc.1"
desugarNio = "2.1.5"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

[libraries]
picacomic-core = { module = "io.github.jukomu:picacomic-core", version.ref = "picacomic" }
desugar-nio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugarNio" }
